export const WeatherIconDescriptions:Descriptions = {    
    "1": "Selkeää",
    "2": "Enimmäkseen selkeää",
    "3": "Pilvistä",
    "4": "Puolipilvistä",
    "6": "Enimmäkseen pilvistä",
    "7": "Pilvistä",
    "9": "Sumua",
    "11": "Tihkusadetta",
    "14": "Jäätävää tihkua",
    "17": "Jäätävää sadetta",
    "21": "Yksittäisia sadekuuroja",
    "23": "Sadekuuroja",
    "24": "Paikoin sadekuuroja",
    "27": "Sadekuuroja",
    "31": "Puolipilvistä ja ajoittain heikkoa vesisadetta",
    "32": "Puolipilvistä ja ajoittain kohtalaista vesisadetta",
    "33": "Puolipilvistä ja ajoittain voimakasta vesisadetta",
    "34": "enimmäkseen pilvistä ja ajoittain heikkoa vesisadetta",
    "35": "enimmäkseen pilvistä ja ajoittain kohtalaista vesisadetta",
    "36": "enimmäkseen pilvistä ja ajoittain voimakasta vesisadetta",  
    "37": "heikkoa vesisadetta",
    "38": "kohtalaista vesisadetta",
    "39": "voimakasta vesisadetta",
    "41": "puolipilvistä ja ajoittain heikkoa räntäsadetta tai räntäkuuroja",
    "42": "puolipilvistä ja ajoittain kohtalaista räntäsadetta tai räntäkuuroja",
    "43": "puolipilvistä ja ajoittain voimakasta räntäsadetta tai räntäkuuroja",
    "44": "enimmäkseen pilvistä ja ajoittain heikkoa räntäsadetta tai räntäkuuroja",
    "45": "enimmäkseen pilvistä ja ajoittain kohtalaista räntäsadetta tai räntäkuuroja",
    "46": "enimmäkseen pilvistä ja ajoittain voimakasta räntäsadetta tai räntäkuuroja",
    "47": "heikkoa räntäsadetta",
    "48": "kohtalaista räntäsadetta",
    "49": "voimakasta räntäsadetta",
    "51": "puolipilvistä ja ajoittain heikkoa lumisadetta tai lumikuuroja",
    "52": "enimmäkseen pilvistä ja ajoittain kohtalaista lumisadetta tai lumikuuroja",
    "53": "enimmäkseen pilvistä ja ajoittain sakeaa lumisadetta tai lumikuuroja",
    "54": "enimmäkseen pilvistä ja ajoittain heikkoa lumisadetta tai lumikuuroja",
    "55": "enimmäkseen pilvistä ja ajoittain kohtalaista lumisadetta tai lumikuuroja",
    "56": "enimmäkseen pilvistä ja ajoittain sakeaa lumisadetta tai lumikuuroja",
    "57": "heikkoa lumisadetta",
    "58": "kohtalaista lumisadetta",
    "59": "runsasta lumisadetta",
    "61": "yksittäisiä raekuuroja",
    "63": "Ukostaa",
    "64": "paikoin raekuuroja",
    "67": "raekuuroja",
    "71": "yksittäisiä ukkoskuuroja",
    "74": "paikoin ukkoskuuroja",
    "77": "ukkoskuuroja",
    "82": "Loskakeli",
    "91": "Sumua",
}
interface Descriptions {
    [key: string]: string;
}